export const MOCK_PROJECT = {
    id: "proj_pilot",
    name: "代書事務所與 AI 輔助 Pilot Program",
    description: "本專案旨在為代書事務所導入結構，透過建立最小可行專案資料庫（MVP）、會議 SSOT 與 AI 輔助機制，驗證組織轉型之可行性。",
    oneSentence: "建立可持續的專案節奏，以 AI 賦能達成輕量化。",
    status: "Pilot 啟動中",
    currentPhase: "Phase 0：現況盤點與邊界設定",
    scopeIn: [
        "單一案件類型專屬流程 (Pilot)",
        "專案資料庫建置 (Table-based)",
        "每週案件盤點會議節奏",
        "Line 記事本 SSOT 標準化",
        "客戶對話匿名化分析",
        "AI 回覆建議 (人工審核)",
        "基本風險報表生成"
    ],
    scopeOut: [
        "全事務所系統硬性替換",
        "財務與會計系統整合",
        "AI 自動直連發送訊息",
        "客戶端專屬 App 開發"
    ],
    rhythm: "每週二案件盤點（30 分鐘）、每週五風險提醒報告、每日自動清單。",
};

export const MOCK_PLANS = [
    {
        id: "plan_100",
        name: "基礎節奏導入",
        fee: "100,000 NTD",
        scope: "建立 1 種核心流程模型",
        dbSetup: "完整版專案資料庫",
        rhythm: "基礎專案節奏設計",
        ssot: "會議紀錄 SSOT 建立",
        riskAlerts: "文件型提醒（內容比對）",
        profiling: "無",
        kpi: "基礎效能指標",
        training: "2 次實作培訓",
        period: "3 個月陪跑",
        maturity: "基礎治理結構確立",
    },
    {
        id: "plan_180",
        name: "成長優化導入",
        fee: "180,000 NTD",
        scope: "建立 3 種主要流程模型",
        dbSetup: "完整版專案資料庫",
        rhythm: "優化決策流程設計",
        ssot: "跨部門 SSOT 建立",
        riskAlerts: "規則型提醒（流程觸發）",
        profiling: "客戶輪廓分析 (含)",
        kpi: "多維度效能指標",
        training: "3 次實作培訓",
        period: "5 個月陪跑",
        maturity: "流程標準化與規則優化",
    },
    {
        id: "plan_250",
        name: "轉型自動化導入",
        fee: "250,000 NTD",
        scope: "建立 10 以內流程體系",
        dbSetup: "完整版專案資料庫",
        rhythm: "全量節奏",
        ssot: "AI 賦能 SSOT 集成",
        riskAlerts: "模型判斷型提醒 (分析觸發)",
        profiling: "深度客戶分析 (含)",
        kpi: "全視角預測看板",
        training: "3–4 次深度培訓",
        period: "6 個月陪跑",
        maturity: "極高：包含 COSO 風險觀測、ISO9001 資料可追溯、GRPI 團隊發展",
    },
];

export const MOCK_PHASES = [
    {
        index: 0,
        objective: "現況盤點與邊界設定",
        actions: ["繪製案件流程圖", "選定 Pilot 案件類型", "確定會議節奏與權責"],
        deliverables: ["現況流程圖", "Pilot 範圍定義文件"],
        impact: "明確 Pilot 邊界，建立初步數位透明度基礎。",
    },
    {
        index: 1,
        objective: "專案資料庫建置",
        actions: ["建置 Projects Table", "定義案件階段 (Stages)", "資料全量匯入"],
        deliverables: ["專案資料庫 (Supabase/Airtable)", "Stage 定義手冊"],
        impact: "案件資訊從口頭與 Line 轉向統一結構化資料庫。",
    },
    {
        index: 2,
        objective: "專案節奏與會議 SSOT",
        actions: ["固定週二盤點會議", "制定 Line 記事本標準格式", "自動生成風險清單"],
        deliverables: ["標準化會議記錄", "風險清單報表"],
        impact: "決議可追蹤，案件延誤可預警。",
    },
    {
        index: 3,
        objective: "客戶輪廓與 AI 回覆建議",
        actions: ["建立客戶分類模型", "Line 對話分析實驗", "AI 回覆建議測試"],
        deliverables: ["客戶輪廓分析報告", "AI 輔助溝通指南"],
        impact: "縮短客戶焦慮回覆時間，提升溝通效率與品質。",
    },
    {
        index: 4,
        objective: "員工回饋與組織報告",
        actions: ["收集員工壓力回饋", "生成月度節奏報告", "Pilot 總結與檢核"],
        deliverables: ["月度節奏報告", "Pilot 成功驗證文件"],
        impact: "形成閉環治理，達成組織持續演進與轉型。",
    },
];
